### ISSUE TITLE
Invalid dependency

### ISSUE THREAD

**Issue by monkeyhouse** [Anderman/Mvc.JQuery.Datatables#1]
After installing, there is an error message
"The dependency Microsoft.Net.Http.Client >= 1.0.0-beta6-15001 could not be resolved."
I dont think Microsoft.Net.Http.Client library exists on nuget.

**Comment by Anderman** [comment]
Sorry you need an another nuget feed.
https://www.myget.org/F/aspnetrelease/api/v2
see https://ci.appveyor.com/project/Anderman/mvc-jquery-datatables
